[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family = "Roboto Mono Nerd Font"
bold.family = "Roboto Mono Nerd Font"
italic.family = "Roboto Mono Nerd Font"
bold_italic.family = "Roboto Mono Nerd Font"

size = 10.0

[colors]
primary = { background = "#161616", foreground = "#ffffff" }

[colors.search.matches]
foreground = "CellBackground"
background = "#ee5396"

[colors.footer_bar]
background = "#262626"
foreground = "#ffffff"

[colors.normal]
black = "#262626"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"

[colors.bright]
black = "#393939"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#ffffff"
